# Generated by Django 3.2.16 on 2022-10-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoAlbum', '0002_comment_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_approve',
            field=models.BooleanField(default=False),
        ),
    ]
