# Generated by Django 3.2.16 on 2022-10-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoAlbum', '0003_comment_is_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='album_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
